config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :user_backoffice, path: :principal do
    get 'homes/index'
    resources :yields, path: :rendimentos
  end
  root to: 'user_backoffice/homes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  self.table_name = "gamedesk.comments"

  belongs_to :ticket, class_name: "Ticket", foreign_key: :ticket_id
end

app/models/requester.rb
class Requester < ApplicationRecord
  self.table_name = "gamedesk.requesters"

  has_many :tickets, class_name: "Ticket", foreign_key: :requester_id, primary_key: :requester_id
end

app/models/submitter.rb
class Submitter < ApplicationRecord
  self.table_name = "gamedesk.submitters"

  has_many :tickets, class_name: "Ticket", foreign_key: :submitter_id, primary_key: :submitter_id
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  self.table_name = "gamedesk.tickets"

  has_many :comments, class_name: "Comment", foreign_key: :ticket_id
  belongs_to :submitter, class_name: "Submitter", foreign_key: :submitter_id, primary_key: :submitter_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_backoffice.rb
module UserBackoffice
  def self.table_name_prefix
    'user_backoffice_'
  end
end

app/models/user_backoffice/yield.rb
class UserBackoffice::Yield < ApplicationRecord
  self.table_name = "gamedesk.yields"
  belongs_to :submitter, class_name: "Submitter", foreign_key: :submitter_id, primary_key: :submitter_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/user_backoffice/homes_controller.rb
class UserBackoffice::HomesController < UserBackofficesController
  def index
    PopulaTabelaService.new(nil).execute
  end
end

app/controllers/user_backoffice/yields_controller.rb
class UserBackoffice::YieldsController < UserBackofficesController
  before_action :set_user_backoffice_yield, only: %i[ show edit update destroy ]

  # GET /user_backoffice/yields or /user_backoffice/yields.json
  def index
    @user_backoffice_yields = UserBackoffice::Yield.eager_load(:submitter).all
  end

  # GET /user_backoffice/yields/1 or /user_backoffice/yields/1.json
  def show
  end

  # GET /user_backoffice/yields/new
  def new
    @user_backoffice_yield = UserBackoffice::Yield.new
  end

  # GET /user_backoffice/yields/1/edit
  def edit
  end

  # POST /user_backoffice/yields or /user_backoffice/yields.json
  def create
    @user_backoffice_yield = UserBackoffice::Yield.new(user_backoffice_yield_params)

    respond_to do |format|
      if @user_backoffice_yield.save
        format.html { redirect_to @user_backoffice_yield, notice: "Yield was successfully created." }
        format.json { render :show, status: :created, location: @user_backoffice_yield }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_backoffice_yield.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_backoffice/yields/1 or /user_backoffice/yields/1.json
  def update
    respond_to do |format|
      if @user_backoffice_yield.update(user_backoffice_yield_params)
        format.html { redirect_to @user_backoffice_yield, notice: "Yield was successfully updated." }
        format.json { render :show, status: :ok, location: @user_backoffice_yield }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_backoffice_yield.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_backoffice/yields/1 or /user_backoffice/yields/1.json
  def destroy
    @user_backoffice_yield.destroy
    respond_to do |format|
      format.html { redirect_to user_backoffice_yields_url, notice: "Yield was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user_backoffice_yield
    @user_backoffice_yield = UserBackoffice::Yield.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_backoffice_yield_params
    params.require(:user_backoffice_yield).permit(:id, :submitter_id, :level, :xp)
  end
end

app/controllers/user_backoffices_controller.rb
class UserBackofficesController < ApplicationController
  layout 'user_backoffice'
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_backoffice/homes_helper.rb
module UserBackoffice::HomesHelper
end

app/helpers/user_backoffice/yields_helper.rb
module UserBackoffice::YieldsHelper
end

app/helpers/user_backoffice_helper.rb
module UserBackofficeHelper
end

app/views/layouts/_content_wapper.html.erb
<div id="content-wrapper" class="d-flex flex-column">

  <!-- Main Content -->
  <div id="content">
    <%= render 'layouts/top_bar' %>
    <!-- Begin Page Content -->
    <div class="container-fluid">
      <%= yield %>
    </div>
  </div>
  <!-- End of Main Content -->

  <%= render 'layouts/footer' %>

</div>

app/views/layouts/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Gamedesk 2021</span>
    </div>
  </div>
</footer>

app/views/layouts/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-info sidebar sidebar-dark accordion" id="accordionSidebar">

  <%= link_to root_path, class: 'sidebar-brand d-flex align-items-center justify-content-center' do %>
    <%= image_tag 'gamedesk_icon_white.png', size: "45x57" %>
    <div class="sidebar-brand-text">Gamedesk</div>
  <% end %>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="index.html">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <%= link_to user_backoffice_yields_path, class: 'nav-link' do %>
      <i class="fas fa-chart-line"></i>
      <span>Rendimentos</span>
    <% end %>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Administração
  </div>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
       aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Cadastros Básicos</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
         data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Manutenção:</h6>
        <a class="collapse-item" href="utilities-color.html">Usuários</a>
      </div>
    </div>
  </li>


  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

app/views/layouts/_top_bar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
           aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small"
                   placeholder="Search for..." aria-label="Search"
                   aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-info" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
           aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alerts Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
           aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="img/undraw_profile_1.svg"
                 alt="...">
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a
              problem I've been having.
            </div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="img/undraw_profile_2.svg"
                 alt="...">
            <div class="status-indicator"></div>
          </div>
          <div>
            <div class="text-truncate">I have the photos that you ordered last month, how
              would you like them sent to you?
            </div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="img/undraw_profile_3.svg"
                 alt="...">
            <div class="status-indicator bg-warning"></div>
          </div>
          <div>
            <div class="text-truncate">Last month's report looks great, I am very happy with
              the progress so far, keep up the good work!
            </div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                 alt="...">
            <div class="status-indicator bg-success"></div>
          </div>
          <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone
              told me that people say this to all dogs, even if they aren't good...
            </div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
      </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Douglas McGee</span>
        <img class="img-profile rounded-circle"
             src="img/undraw_profile.svg">
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
           aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Sair
        <% end %>
        <!--        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">-->

        <!--        </a>-->
      </div>
    </li>

  </ul>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Gamedesk - Login</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'user_backoffice' %>

</head>

<body class="bg-gradient-info">

<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-10 col-lg-6 col-md-9">
      <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
          <div class="row">

            <div class="col-lg-12">
              <div class="p-5">
                <div class="text-center">
                  <%= image_tag 'gamedesk_icon_black.png', size: "70x88" %>
                  <h1 class="h4 text-gray-900 mb-4">Login</h1>
                </div>
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'user_backoffice' %>

</body>

</html>

app/views/layouts/user_backoffice.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>GameDesk</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application' %>
  <%= stylesheet_link_tag 'user_backoffice' %>

</head>

<body id="page-top">

<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <%= render 'layouts/sidebar' %>
  <!-- End of Sidebar -->

  <!-- Content Wrapper -->
  <%= render 'layouts/content_wapper' %>
  <!-- End of Content Wrapper -->

</div>
<!-- End of Page Wrapper -->

<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fas fa-angle-up"></i>
</a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <a class="btn btn-info" href="login.html">Logout</a>
      </div>
    </div>
  </div>
</div>
<%= javascript_include_tag 'application' %>
<%= javascript_include_tag 'user_backoffice' %>
</body>

</html>

app/views/user_backoffice/homes/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Charts</h1>
<p class="mb-4">Chart.js is a third party plugin that is used to generate the charts in this theme.
  The charts below have been customized - for further customization options, please visit the <a
  target="_blank" href="https://www.chartjs.org/docs/latest/">official Chart.js
  documentation</a>.</p>

<!-- Content Row -->
<div class="row">

  <div class="col-xl-8 col-lg-7">

    <!-- Area Chart -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Area Chart</h6>
      </div>
      <div class="card-body">
        <div class="chart-area">
          <canvas id="myAreaChart"></canvas>
        </div>
        <hr>
        Styling for the area chart can be found in the
        <code>/js/demo/chart-area-demo.js</code> file.
      </div>
    </div>

    <!-- Bar Chart -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Bar Chart</h6>
      </div>
      <div class="card-body">
        <div class="chart-bar">
          <canvas id="myBarChart"></canvas>
        </div>
        <hr>
        Styling for the bar chart can be found in the
        <code>/js/demo/chart-bar-demo.js</code> file.
      </div>
    </div>

  </div>

  <!-- Donut Chart -->
  <div class="col-xl-4 col-lg-5">
    <div class="card shadow mb-4">
      <!-- Card Header - Dropdown -->
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Donut Chart</h6>
      </div>
      <!-- Card Body -->
      <div class="card-body">
        <div class="chart-pie pt-4">
          <canvas id="myPieChart"></canvas>
        </div>
        <hr>
        Styling for the donut chart can be found in the
        <code>/js/demo/chart-pie-demo.js</code> file.
      </div>
    </div>
  </div>
</div>

app/views/user_backoffice/yields/_form.html.erb
<%= form_with(model: user_backoffice_yield, local: true) do |form| %>
  <% if user_backoffice_yield.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_backoffice_yield.errors.count, "error") %> prohibited this user_backoffice_yield from being saved:</h2>

      <ul>
      <% user_backoffice_yield.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_backoffice/yields/edit.html.erb
<h1>Editing User Backoffice Yield</h1>

<%= render 'form', user_backoffice_yield: @user_backoffice_yield %>

<%= link_to 'Show', @user_backoffice_yield %> |
<%= link_to 'Back', user_backoffice_yields_path %>

app/views/user_backoffice/yields/index.html.erb
<h1>Rendimentos dos Funcionários</h1>

<div class="card shadow mb-4">
  <div class="card-header py-3">
    <div class="row">
      <div class="col-md-10">
        <h6 class="m-0 font-weight-bold text-primary">Lista de Rendimentos</h6>
      </div>
      <div class="col-md-2">
        <%#= link_to new_user_backoffice_yield_path, class: 'btn btn-primary btn-icon-split btn-sm float-right' do %>
<!--          <span class="icon text-white-50"><i class="fas fa-plus-circle"></i></span>-->
<!--          <span class="text">Novo</span>-->
        <%# end %>
      </div>
    </div>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered dataTable" width="100%" cellspacing="0">
        <thead>
        <tr>
          <th>Nome</th>
          <th>Level</th>
          <th>Xp</th>
          <th>Ações</th>
        </tr>
        </thead>
        <tbody style="font-weight: bold">
        <% @user_backoffice_yields.each do |user_backoffice_yield| %>
          <tr>
            <td><%= user_backoffice_yield&.submitter&.name %></td>
            <td><%= user_backoffice_yield.level %></td>
            <td><%= user_backoffice_yield.xp %></td>
            <td>
              <%= link_to 'Show', user_backoffice_yield %>
              <%= link_to 'Edit', edit_user_backoffice_yield_path(user_backoffice_yield) %>
              <%= link_to 'Destroy', user_backoffice_yield, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<br>

app/views/user_backoffice/yields/new.html.erb
<h1>New User Backoffice Yield</h1>

<%= render 'form', user_backoffice_yield: @user_backoffice_yield %>

<%= link_to 'Back', user_backoffice_yields_path %>

app/views/user_backoffice/yields/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_user_backoffice_yield_path(@user_backoffice_yield) %> |
<%= link_to 'Back', user_backoffice_yields_path %>